version: '3.8'

services:
  postgres:
    image: postgres:17.5-alpine3.21
    container_name: INote-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: INote-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: INote-app
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_ADDR: redis:6379
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
